/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ContentEnginePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/AnalyzeModal.ts
var import_obsidian2 = require("obsidian");

// src/PublishResultModal.ts
var import_obsidian = require("obsidian");
var PublishResultModal = class extends import_obsidian.Modal {
  constructor(app, results) {
    super(app);
    this.results = results;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("content-engine-result-modal");
    contentEl.createEl("h2", { text: "\uAC8C\uC2DC \uACB0\uACFC" });
    const list = contentEl.createEl("div", { cls: "content-engine-result-list" });
    for (const result of this.results) {
      const row = list.createEl("div", { cls: "content-engine-result-row" });
      row.createEl("strong", { text: result.platform });
      if (result.success) {
        row.createSpan({ cls: "content-engine-badge content-engine-badge-published", text: "published" });
        if (result.url) {
          row.createEl("a", {
            text: "\uAC8C\uC2DC\uBB3C \uC5F4\uAE30",
            href: result.url
          });
        }
      } else {
        row.createSpan({ cls: "content-engine-badge content-engine-badge-error", text: "error" });
        row.createEl("p", { text: result.error || "\uC54C \uC218 \uC5C6\uB294 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4." });
      }
    }
    contentEl.createEl("button", { text: "\uB2EB\uAE30", cls: "mod-cta" }).addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/AnalyzeModal.ts
var TAB_LABELS = {
  blog: "Blog",
  video: "YouTube",
  threads: "Threads",
  instagram: "Instagram",
  twitter: "Twitter/X",
  github: "GitHub"
};
var AnalyzeModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, initialFile) {
    super(app);
    this.files = [];
    this.selectedPaths = /* @__PURE__ */ new Set();
    this.analyzeResult = null;
    this.blog = null;
    this.video = null;
    this.socials = {};
    this.statuses = {
      blog: "pending",
      video: "pending",
      threads: "pending",
      instagram: "pending",
      twitter: "pending",
      github: "pending"
    };
    this.activeTab = "blog";
    this.plugin = plugin;
    if (initialFile) {
      this.selectedPaths.add(initialFile.path);
    }
  }
  onOpen() {
    this.files = this.app.vault.getMarkdownFiles().sort((a, b) => a.path.localeCompare(b.path));
    this.contentEl.addClass("content-engine-modal");
    this.renderFilePicker();
  }
  onClose() {
    this.contentEl.empty();
  }
  renderFilePicker() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Content Engine" });
    contentEl.createEl("p", { text: "\uBD84\uC11D\uD560 \uB178\uD2B8\uB97C \uC120\uD0DD\uD558\uC138\uC694. \uC5EC\uB7EC \uAC1C\uB97C \uD568\uAED8 \uBCF4\uB0BC \uC218 \uC788\uC2B5\uB2C8\uB2E4." });
    const toolbar = contentEl.createEl("div", { cls: "content-engine-toolbar" });
    toolbar.createEl("button", { text: "\uC804\uCCB4 \uC120\uD0DD" }).addEventListener("click", () => {
      this.files.forEach((file) => this.selectedPaths.add(file.path));
      this.renderFilePicker();
    });
    toolbar.createEl("button", { text: "\uC120\uD0DD \uD574\uC81C" }).addEventListener("click", () => {
      this.selectedPaths.clear();
      this.renderFilePicker();
    });
    const fileList = contentEl.createEl("div", { cls: "content-engine-file-list" });
    if (this.files.length === 0) {
      fileList.createEl("p", { text: "Vault\uC5D0\uC11C Markdown \uD30C\uC77C\uC744 \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4." });
    }
    for (const file of this.files) {
      const row = fileList.createEl("label", { cls: "content-engine-file-row" });
      const checkbox = row.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedPaths.has(file.path);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedPaths.add(file.path);
        } else {
          this.selectedPaths.delete(file.path);
        }
      });
      row.createSpan({ text: file.path });
    }
    const analyzeButton = contentEl.createEl("button", { text: "Analyze", cls: "mod-cta content-engine-primary" });
    analyzeButton.disabled = this.files.length === 0;
    analyzeButton.addEventListener("click", () => void this.analyzeSelectedNotes());
  }
  async analyzeSelectedNotes() {
    const selectedFiles = this.files.filter((file) => this.selectedPaths.has(file.path));
    if (selectedFiles.length === 0) {
      new import_obsidian2.Notice("\uBD84\uC11D\uD560 \uB178\uD2B8\uB97C \uD558\uB098 \uC774\uC0C1 \uC120\uD0DD\uD558\uC138\uC694.");
      return;
    }
    this.renderLoading("\uB178\uD2B8\uB97C \uBD84\uC11D\uD558\uB294 \uC911...");
    try {
      const notes = await Promise.all(
        selectedFiles.map(async (file) => ({
          filename: file.path,
          content: await this.app.vault.read(file)
        }))
      );
      const model = this.getModel();
      this.analyzeResult = await this.request("/api/analyze", { notes, model });
      await this.generateAll();
      this.renderResults();
    } catch (error) {
      this.showError(error, "\uBD84\uC11D \uC911 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.");
      this.renderFilePicker();
    }
  }
  getModel() {
    const { selectedModel, customModel } = this.plugin.settings;
    return selectedModel === "custom" ? customModel : selectedModel;
  }
  async generateAll() {
    if (!this.analyzeResult) return;
    this.renderLoading("\uCF58\uD150\uCE20\uB97C \uC0DD\uC131\uD558\uB294 \uC911...");
    const base = {
      insights: this.analyzeResult.insights,
      summary: this.analyzeResult.summary,
      model: this.getModel()
    };
    const socialPlatforms = [];
    if (this.plugin.settings.platforms.threads) socialPlatforms.push("threads");
    if (this.plugin.settings.platforms.instagram) socialPlatforms.push("instagram");
    if (this.plugin.settings.platforms.twitter) socialPlatforms.push("twitter");
    if (this.plugin.settings.platforms.github) socialPlatforms.push("github");
    try {
      const tasks = [];
      if (this.blog === null) {
        tasks.push(
          this.request("/api/generate/blog", {
            ...base,
            template: this.plugin.settings.templates.blog
          }).then((result) => this.blog = result)
        );
      }
      if (this.plugin.settings.platforms.youtube && this.video === null) {
        tasks.push(
          this.request("/api/generate/video", {
            ...base,
            template: this.plugin.settings.templates.youtube
          }).then((result) => this.video = result)
        );
      }
      for (const platform of socialPlatforms) {
        if (this.socials[platform] === void 0) {
          tasks.push(
            this.request("/api/generate/social", {
              ...base,
              platform,
              template: this.plugin.settings.templates[platform]
            }).then((content) => {
              this.socials[platform] = content;
            })
          );
        }
      }
      await Promise.all(tasks);
    } catch (error) {
      this.showError(error, "\uCF58\uD150\uCE20 \uC0DD\uC131 \uC911 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.");
      throw error;
    }
  }
  renderResults() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\uBD84\uC11D \uACB0\uACFC" });
    if (!this.analyzeResult) return;
    const summary = contentEl.createEl("div", { cls: "content-engine-summary" });
    summary.createEl("h3", { text: "\uC694\uC57D" });
    summary.createEl("p", { text: this.analyzeResult.summary });
    const details = contentEl.createEl("details", { cls: "content-engine-insights" });
    details.createEl("summary", { text: `\uC778\uC0AC\uC774\uD2B8 ${this.analyzeResult.insights.length}\uAC1C` });
    const list = details.createEl("ol");
    for (const insight of this.analyzeResult.insights) {
      list.createEl("li", { text: insight });
    }
    const tabs = contentEl.createEl("div", { cls: "content-engine-tabs" });
    Object.keys(TAB_LABELS).forEach((tab) => {
      const button = tabs.createEl("button", {
        text: TAB_LABELS[tab],
        cls: tab === this.activeTab ? "is-active" : ""
      });
      button.addEventListener("click", () => {
        this.activeTab = tab;
        this.renderResults();
      });
    });
    const tabContainer = contentEl.createEl("div", { cls: "content-engine-tab-panel" });
    void this.renderTab(tabContainer, this.activeTab);
    const bottom = contentEl.createEl("div", { cls: "content-engine-bottom-bar" });
    bottom.createEl("button", { text: "Publish All", cls: "mod-cta" }).addEventListener("click", () => void this.publishAll());
  }
  async renderTab(container, tab) {
    container.empty();
    const header = container.createEl("div", { cls: "content-engine-tab-header" });
    header.createEl("h3", { text: TAB_LABELS[tab] });
    header.createSpan({ cls: `content-engine-badge content-engine-badge-${this.statuses[tab]}`, text: this.statuses[tab] });
    const preview = container.createEl("div", { cls: "content-engine-preview" });
    if (tab === "blog") {
      await this.renderBlog(preview);
    } else if (tab === "video") {
      this.renderVideo(preview);
    } else {
      this.renderSocial(preview, tab);
    }
    const actions = container.createEl("div", { cls: "content-engine-actions" });
    actions.createEl("button", { text: "Regenerate" }).addEventListener("click", () => void this.regenerate(tab));
    actions.createEl("button", { text: "Publish", cls: "mod-cta" }).addEventListener("click", () => void this.publish(tab));
  }
  async renderBlog(container) {
    if (!this.blog) {
      container.createEl("p", { text: "\uBE14\uB85C\uADF8 \uCF58\uD150\uCE20\uAC00 \uC544\uC9C1 \uC0DD\uC131\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." });
      return;
    }
    container.createEl("h2", { text: this.blog.title });
    const tags = container.createEl("p", { cls: "content-engine-tags" });
    tags.setText(this.blog.tags.map((tag) => `#${tag.replace(/^#/, "")}`).join(" "));
    const rendered = container.createEl("div", { cls: "content-engine-markdown" });
    await import_obsidian2.MarkdownRenderer.render(this.app, this.blog.content, rendered, "content-engine-blog.md", this.plugin);
  }
  renderVideo(container) {
    if (!this.video) {
      container.createEl("p", { text: "\uC720\uD29C\uBE0C \uC2A4\uD06C\uB9BD\uD2B8\uAC00 \uC544\uC9C1 \uC0DD\uC131\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." });
      return;
    }
    container.createEl("h2", { text: this.video.title });
    container.createEl("h4", { text: "Description" });
    container.createEl("p", { text: this.video.description });
    container.createEl("h4", { text: "Script" });
    container.createEl("pre", { text: this.video.script });
    container.createEl("p", { cls: "content-engine-tags", text: this.video.tags.map((tag) => `#${tag.replace(/^#/, "")}`).join(" ") });
  }
  renderSocial(container, platform) {
    const content = this.socials[platform];
    if (!content) {
      container.createEl("p", { text: `${TAB_LABELS[platform]} \uCF58\uD150\uCE20\uAC00 \uC544\uC9C1 \uC0DD\uC131\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.` });
      return;
    }
    container.createEl("pre", { text: content.caption });
    container.createEl("p", { cls: "content-engine-tags", text: content.hashtags.map((tag) => `#${tag.replace(/^#/, "")}`).join(" ") });
  }
  async regenerate(tab) {
    if (!this.analyzeResult) return;
    const base = {
      insights: this.analyzeResult.insights,
      summary: this.analyzeResult.summary,
      model: this.getModel()
    };
    this.renderLoading(`${TAB_LABELS[tab]} \uCF58\uD150\uCE20\uB97C \uB2E4\uC2DC \uC0DD\uC131\uD558\uB294 \uC911...`);
    try {
      if (tab === "blog") {
        this.blog = await this.request("/api/generate/blog", {
          ...base,
          template: this.plugin.settings.templates.blog
        });
      } else if (tab === "video") {
        this.video = await this.request("/api/generate/video", {
          ...base,
          template: this.plugin.settings.templates.youtube
        });
      } else {
        this.socials[tab] = await this.request("/api/generate/social", {
          ...base,
          platform: tab,
          template: this.plugin.settings.templates[tab]
        });
      }
      this.statuses[tab] = "pending";
      this.renderResults();
    } catch (error) {
      this.showError(error, "\uB2E4\uC2DC \uC0DD\uC131 \uC911 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.");
      this.renderResults();
    }
  }
  async publish(tab) {
    if (tab !== "blog" && tab !== "video") {
      const platformKey = tab;
      if (!this.plugin.settings.platforms[platformKey]) {
        const result = { platform: tab, success: false, error: `${TAB_LABELS[tab]}\uB294 \uBE44\uD65C\uC131\uD654\uB41C \uD50C\uB7AB\uD3FC\uC785\uB2C8\uB2E4.` };
        new import_obsidian2.Notice(result.error);
        return result;
      }
    }
    if (tab === "video" && !this.plugin.settings.platforms.youtube) {
      const result = { platform: tab, success: false, error: "YouTube\uB294 \uBE44\uD65C\uC131\uD654\uB41C \uD50C\uB7AB\uD3FC\uC785\uB2C8\uB2E4." };
      new import_obsidian2.Notice(result.error);
      return result;
    }
    const content = this.getPublishContent(tab);
    if (!content) {
      const result = { platform: tab, success: false, error: "\uAC8C\uC2DC\uD560 \uCF58\uD150\uCE20\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4." };
      new import_obsidian2.Notice(result.error);
      return result;
    }
    this.statuses[tab] = "publishing";
    this.renderResults();
    try {
      const templateKey = tab === "video" ? "youtube" : tab;
      const result = await this.request("/api/publish", {
        platform: tab,
        content,
        template: this.plugin.settings.templates[templateKey],
        model: this.getModel()
      });
      this.statuses[tab] = result.success ? "published" : "error";
      this.renderResults();
      if (result.success) {
        new import_obsidian2.Notice(`${TAB_LABELS[tab]} \uAC8C\uC2DC \uC644\uB8CC`);
      } else {
        new import_obsidian2.Notice(result.error || `${TAB_LABELS[tab]} \uAC8C\uC2DC \uC2E4\uD328`);
      }
      return { ...result, platform: tab };
    } catch (error) {
      this.statuses[tab] = "error";
      this.renderResults();
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian2.Notice(`${TAB_LABELS[tab]} \uAC8C\uC2DC \uC2E4\uD328: ${message}`);
      return { platform: tab, success: false, error: message };
    }
  }
  async publishAll() {
    const tabs = [];
    if (this.blog) tabs.push("blog");
    if (this.video && this.plugin.settings.platforms.youtube) tabs.push("video");
    if (this.socials.threads && this.plugin.settings.platforms.threads) tabs.push("threads");
    if (this.socials.instagram && this.plugin.settings.platforms.instagram) tabs.push("instagram");
    if (this.socials.twitter && this.plugin.settings.platforms.twitter) tabs.push("twitter");
    if (this.socials.github && this.plugin.settings.platforms.github) tabs.push("github");
    if (tabs.length === 0) {
      new import_obsidian2.Notice("\uAC8C\uC2DC\uD560 \uCF58\uD150\uCE20\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    const results = [];
    for (const tab of tabs) {
      results.push(await this.publish(tab));
    }
    new PublishResultModal(this.app, results).open();
  }
  getPublishContent(tab) {
    if (tab === "blog") {
      if (!this.blog) return null;
      return {
        caption: `# ${this.blog.title}

${this.blog.content}`,
        hashtags: this.blog.tags
      };
    }
    if (tab === "video") {
      if (!this.video) return null;
      return {
        caption: `${this.video.title}

${this.video.description}

${this.video.script}`,
        hashtags: this.video.tags
      };
    }
    return this.socials[tab] || null;
  }
  renderLoading(message) {
    this.contentEl.empty();
    const loading = this.contentEl.createEl("div", { cls: "content-engine-loading" });
    loading.createEl("h2", { text: message });
    loading.createEl("p", { text: "\uC7A0\uC2DC\uB9CC \uAE30\uB2E4\uB824 \uC8FC\uC138\uC694." });
  }
  async request(path, body) {
    const baseUrl = this.plugin.settings.apiUrl.replace(/\/$/, "");
    const response = await fetch(`${baseUrl}${path}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    });
    if (!response.ok) {
      const text = await response.text();
      throw new Error(`${response.status} ${response.statusText}${text ? `: ${text}` : ""}`);
    }
    return await response.json();
  }
  showError(error, fallback) {
    const message = error instanceof Error ? error.message : String(error || fallback);
    new import_obsidian2.Notice(`${fallback}: ${message}`);
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var AVAILABLE_MODELS = [
  { id: "gpt-4", name: "GPT-4" },
  { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
  { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo" },
  { id: "claude-3-opus", name: "Claude 3 Opus" },
  { id: "claude-3-sonnet", name: "Claude 3 Sonnet" },
  { id: "claude-3-haiku", name: "Claude 3 Haiku" },
  { id: "deepseek-chat", name: "DeepSeek Chat" },
  { id: "deepseek-coder", name: "DeepSeek Coder" },
  { id: "custom", name: "\uC9C1\uC811 \uC785\uB825" }
];
var DEFAULT_SETTINGS = {
  apiUrl: "http://localhost:8000",
  vaultPath: "",
  platforms: {
    instagram: true,
    threads: true,
    youtube: true,
    twitter: true,
    github: true
  },
  selectedModel: "gpt-4",
  customModel: "",
  templates: {
    blog: "{title}\n\n{content}\n\n#\uBC1C\uD589 #{tags}",
    instagram: "{title}\n\n{summary}\n\n#\uBC1C\uD589 #{tags}",
    threads: "{title}\n\n{content}\n\n{hashtags}",
    youtube: "{title}\n\n{description}\n\n{hashtags}",
    twitter: "{title}\n\n{summary}\n\n{hashtags}",
    github: "{title}\n\n{description}"
  }
};
function detectVaultPath(app) {
  const adapter = app.vault.adapter;
  if (adapter instanceof import_obsidian3.FileSystemAdapter) {
    return adapter.getBasePath();
  }
  return "";
}
var ContentEngineSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Content Engine \uC124\uC815" });
    new import_obsidian3.Setting(containerEl).setName("API URL").setDesc("\uB85C\uCEEC Content Engine \uC6F9 \uC11C\uBE44\uC2A4 \uC8FC\uC18C").addText(
      (text) => text.setPlaceholder("http://localhost:8000").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
        this.plugin.settings.apiUrl = value.trim() || DEFAULT_SETTINGS.apiUrl;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Vault \uACBD\uB85C").setDesc("\uD604\uC7AC \uC635\uC2DC\uB514\uC5B8 vault \uACBD\uB85C\uC785\uB2C8\uB2E4. \uBE44\uC6CC\uB450\uBA74 \uC790\uB3D9 \uAC10\uC9C0\uD569\uB2C8\uB2E4.").addText(
      (text) => text.setPlaceholder(detectVaultPath(this.app) || "\uC790\uB3D9 \uAC10\uC9C0 \uBD88\uAC00").setValue(this.plugin.settings.vaultPath).onChange(async (value) => {
        this.plugin.settings.vaultPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "AI \uBAA8\uB378 \uC124\uC815" });
    new import_obsidian3.Setting(containerEl).setName("LLM \uBAA8\uB378").setDesc("\uC0AC\uC6A9\uD560 AI \uBAA8\uB378\uC744 \uC120\uD0DD\uD569\uB2C8\uB2E4.").addDropdown((dropdown) => {
      AVAILABLE_MODELS.forEach((model) => {
        dropdown.addOption(model.id, model.name);
      });
      dropdown.setValue(this.plugin.settings.selectedModel).onChange(async (value) => {
        this.plugin.settings.selectedModel = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.selectedModel === "custom") {
      new import_obsidian3.Setting(containerEl).setName("\uC0C1\uC138 \uBAA8\uB378\uBA85").setDesc("\uC0AC\uC6A9\uD560 \uC0C1\uC138 \uBAA8\uB378\uBA85\uC744 \uC9C1\uC811 \uC785\uB825\uD569\uB2C8\uB2E4. (\uC608: anthropic/claude-sonnet-4-6)").addText(
        (text) => text.setPlaceholder("anthropic/claude-sonnet-4-6").setValue(this.plugin.settings.customModel).onChange(async (value) => {
          this.plugin.settings.customModel = value.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("\uC5F0\uACB0 \uD14C\uC2A4\uD2B8").setDesc("API \uC11C\uBC84 \uC5F0\uACB0 \uC0C1\uD0DC\uB97C \uD14C\uC2A4\uD2B8\uD569\uB2C8\uB2E4.").addButton((button) => {
      button.setButtonText("\uD14C\uC2A4\uD2B8").setCta().onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("\uD14C\uC2A4\uD2B8 \uC911...");
        try {
          const baseUrl = this.plugin.settings.apiUrl.replace(/\/$/, "");
          const response = await fetch(`${baseUrl}/health`, {
            method: "GET",
            headers: {
              "Content-Type": "application/json"
            }
          });
          if (response.ok) {
            const data = await response.json();
            button.setButtonText("\uC5F0\uACB0 \uC131\uACF5 \u2713");
            button.removeCta();
            setTimeout(() => {
              button.setButtonText("\uD14C\uC2A4\uD2B8");
              button.setCta();
              button.setDisabled(false);
            }, 3e3);
          } else {
            throw new Error(`HTTP ${response.status}`);
          }
        } catch (error) {
          button.setButtonText("\uC5F0\uACB0 \uC2E4\uD328 \u2717");
          button.removeCta();
          setTimeout(() => {
            button.setButtonText("\uD14C\uC2A4\uD2B8");
            button.setCta();
            button.setDisabled(false);
          }, 3e3);
        }
      });
    });
    containerEl.createEl("h3", { text: "\uAC8C\uC2DC \uD50C\uB7AB\uD3FC" });
    this.addPlatformToggle("threads", "Threads");
    this.addPlatformToggle("instagram", "Instagram");
    this.addPlatformToggle("youtube", "YouTube");
    this.addPlatformToggle("twitter", "Twitter/X");
    this.addPlatformToggle("github", "GitHub");
    containerEl.createEl("h3", { text: "\uD50C\uB7AB\uD3FC \uC5F0\uACB0 \uD14C\uC2A4\uD2B8" });
    this.addConnectionTest("threads", "Threads");
    this.addConnectionTest("instagram", "Instagram");
    this.addConnectionTest("youtube", "YouTube");
    this.addConnectionTest("twitter", "Twitter/X");
    this.addConnectionTest("github", "GitHub");
    containerEl.createEl("h3", { text: "\uAC8C\uC2DC \uD15C\uD50C\uB9BF" });
    this.addTemplateEditor("instagram", "Instagram");
    this.addTemplateEditor("threads", "Threads");
    this.addTemplateEditor("youtube", "YouTube");
    this.addTemplateEditor("twitter", "Twitter/X");
    this.addTemplateEditor("github", "GitHub");
    this.addTemplateHelp();
  }
  addPlatformToggle(platform, label) {
    new import_obsidian3.Setting(this.containerEl).setName(label).setDesc(`${label} \uCF58\uD150\uCE20 \uC0DD\uC131/\uAC8C\uC2DC \uAE30\uB2A5 \uC0AC\uC6A9`).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.platforms[platform]).onChange(async (value) => {
        this.plugin.settings.platforms[platform] = value;
        await this.plugin.saveSettings();
      })
    );
  }
  addConnectionTest(platform, label) {
    new import_obsidian3.Setting(this.containerEl).setName(`${label} \uC5F0\uACB0 \uD14C\uC2A4\uD2B8`).setDesc(`${label} API \uC5F0\uACB0 \uC0C1\uD0DC\uB97C \uD14C\uC2A4\uD2B8\uD569\uB2C8\uB2E4.`).addButton((button) => {
      button.setButtonText("\uD14C\uC2A4\uD2B8").setCta().onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("\uD14C\uC2A4\uD2B8 \uC911...");
        try {
          const baseUrl = this.plugin.settings.apiUrl.replace(/\/$/, "");
          const response = await fetch(
            `${baseUrl}/api/test/${platform}`,
            {
              method: "GET",
              headers: {
                "Content-Type": "application/json"
              }
            }
          );
          if (response.ok) {
            const data = await response.json();
            button.setButtonText("\uC5F0\uACB0 \uC131\uACF5 \u2713");
            button.removeCta();
            setTimeout(() => {
              button.setButtonText("\uD14C\uC2A4\uD2B8");
              button.setCta();
              button.setDisabled(false);
            }, 3e3);
          } else {
            throw new Error(`HTTP ${response.status}`);
          }
        } catch (error) {
          button.setButtonText("\uC5F0\uACB0 \uC2E4\uD328 \u2717");
          button.removeCta();
          setTimeout(() => {
            button.setButtonText("\uD14C\uC2A4\uD2B8");
            button.setCta();
            button.setDisabled(false);
          }, 3e3);
        }
      });
    });
  }
  addTemplateEditor(platform, label) {
    const templateKey = platform;
    new import_obsidian3.Setting(this.containerEl).setName(`${label} \uD15C\uD50C\uB9BF`).setDesc(`${label} \uAC8C\uC2DC\uBB3C \uD15C\uD50C\uB9BF\uC785\uB2C8\uB2E4. {title}, {summary}, {content}, {description}, {hashtags}, {tags} \uBCC0\uC218\uB97C \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.`).addTextArea((text) => {
      text.setPlaceholder(`{title}

{summary}

{hashtags}`).setValue(this.plugin.settings.templates[templateKey] || "").onChange(async (value) => {
        this.plugin.settings.templates[templateKey] = value.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
    });
  }
  addTemplateHelp() {
    const helpDiv = this.containerEl.createEl("div", {
      cls: "template-help"
    });
    helpDiv.innerHTML = `
      <h4>\u{1F4DD} \uD15C\uD50C\uB9BF \uBCC0\uC218</h4>
      <ul>
        <li><code>{title}</code> - \uCF58\uD150\uCE20 \uC81C\uBAA9</li>
        <li><code>{summary}</code> - \uC694\uC57D \uD14D\uC2A4\uD2B8</li>
        <li><code>{content}</code> - \uC804\uCCB4 \uCF58\uD150\uCE20</li>
        <li><code>{description}</code> - \uC124\uBA85 \uD14D\uC2A4\uD2B8</li>
        <li><code>{hashtags}</code> - \uD574\uC2DC\uD0DC\uADF8 \uBAA9\uB85D (\uC608: #AI #\uC635\uC2DC\uB514\uC5B8)</li>
        <li><code>{tags}</code> - \uD0DC\uADF8 \uBAA9\uB85D (\uC27C\uD45C\uB85C \uAD6C\uBD84)</li>
      </ul>
      <p><small>\u{1F4A1} \uAC01 \uD50C\uB7AB\uD3FC\uC5D0 \uB9DE\uAC8C \uD15C\uD50C\uB9BF\uC744 \uCEE4\uC2A4\uD130\uB9C8\uC774\uC988\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.</small></p>
    `;
    const style = document.createElement("style");
    style.textContent = `
      .template-help {
        background: var(--background-secondary);
        padding: 16px;
        border-radius: 8px;
        margin: 12px 0;
      }
      .template-help h4 {
        margin: 0 0 8px 0;
        color: var(--text-accent);
      }
      .template-help ul {
        margin: 8px 0;
        padding-left: 20px;
      }
      .template-help li {
        margin: 4px 0;
      }
      .template-help code {
        background: var(--background-primary);
        padding: 2px 6px;
        border-radius: 4px;
        font-family: monospace;
      }
    `;
    this.containerEl.appendChild(style);
  }
};

// src/main.ts
var ContentEnginePlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("rocket", "Content Engine", () => {
      this.openAnalyzeModal();
    });
    this.addCommand({
      id: "analyze-and-publish",
      name: "Analyze & Publish",
      callback: () => this.openAnalyzeModal()
    });
    this.addSettingTab(new ContentEngineSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.platforms = Object.assign({}, DEFAULT_SETTINGS.platforms, this.settings.platforms || {});
    this.settings.templates = Object.assign({}, DEFAULT_SETTINGS.templates, this.settings.templates || {});
    if (!this.settings.vaultPath) {
      this.settings.vaultPath = detectVaultPath(this.app);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openAnalyzeModal() {
    const currentFile = this.app.workspace.getActiveFile();
    if (currentFile && currentFile instanceof import_obsidian4.TFile && currentFile.extension === "md") {
      new AnalyzeModal(this.app, this, currentFile).open();
      return;
    }
    if (this.app.vault.getMarkdownFiles().length === 0) {
      new import_obsidian4.Notice("\uBD84\uC11D\uD560 Markdown \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    new AnalyzeModal(this.app, this, null).open();
  }
};
